name: PostgreSQL service example
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:20-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres  # Matches client.js password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432  # Explicit port mapping

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL
        run: |
          timeout 30 bash -c 'until pg_isready -h postgres -U postgres; do sleep 1; done'

      - name: Connect to PostgreSQL
        run: node client.js
        env:
          POSTGRES_HOST: postgres  # Use service name as host
          POSTGRES_PORT: 5432
