name: PostgreSQL service example
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:20-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install PostgreSQL client tools
        run: |
          apt-get update && apt-get install -y postgresql-client

      - name: Wait for PostgreSQL readiness
        run: |
          pg_isready -h postgres -U postgres -d postgres -t 30

      - name: Run database operations
        run: node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
